version: "3"

services:
  storage:
    image: "mongo"
    ports:
      - "27017:27017"
  api:
    build: .
    restart: always
    command: sh -c "npm install && npm run start"
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - storage
